set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n_i]
set_property IOSTANDARD LVCMOS33 [get_ports dc_i]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sclk_i]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi_i]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs_n_i]
set_property IOSTANDARD LVCMOS33 [get_ports btn0_i]
set_property IOSTANDARD LVCMOS33 [get_ports btn1_i]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_i]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso_o]
set_property IOSTANDARD LVCMOS33 [get_ports led0_r_n_o]
set_property IOSTANDARD LVCMOS33 [get_ports led0_g_n_o]
set_property IOSTANDARD LVCMOS33 [get_ports led0_b_n_o]
set_property IOSTANDARD LVCMOS33 [get_ports led1_o]
set_property IOSTANDARD LVCMOS33 [get_ports led2_o]

set_property PACKAGE_PIN L17 [get_ports clk_i]
set_property PACKAGE_PIN R3 [get_ports rst_n_i]
set_property PACKAGE_PIN T3 [get_ports dc_i]
set_property PACKAGE_PIN R2 [get_ports spi_sclk_i]
set_property PACKAGE_PIN T1 [get_ports spi_mosi_i]
set_property PACKAGE_PIN T2 [get_ports spi_cs_n_i]
set_property PACKAGE_PIN A18 [get_ports btn0_i]
set_property PACKAGE_PIN B18 [get_ports btn1_i]
set_property PACKAGE_PIN J17 [get_ports uart_rx_i]
set_property PACKAGE_PIN J18 [get_ports uart_tx_o]
set_property PACKAGE_PIN U1 [get_ports spi_miso_o]
set_property PACKAGE_PIN C17 [get_ports led0_r_n_o]
set_property PACKAGE_PIN B16 [get_ports led0_g_n_o]
set_property PACKAGE_PIN B17 [get_ports led0_b_n_o]
set_property PACKAGE_PIN A17 [get_ports led1_o]
set_property PACKAGE_PIN C16 [get_ports led2_o]

set_false_path -from [get_ports rst_n_i]
set_false_path -from [get_ports dc_i]
set_false_path -from [get_ports spi_sclk_i]
set_false_path -from [get_ports spi_mosi_i]
set_false_path -from [get_ports spi_cs_n_i]
set_false_path -from [get_ports btn0_i]
set_false_path -from [get_ports btn1_i]
set_false_path -from [get_ports uart_rx_i]
set_false_path -to [get_ports uart_tx_o]
set_false_path -to [get_ports spi_miso_o]
set_false_path -to [get_ports led0_r_n_o]
set_false_path -to [get_ports led0_g_n_o]
set_false_path -to [get_ports led0_b_n_o]
set_false_path -to [get_ports led1_o]
set_false_path -to [get_ports led2_o]
