set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
set_property BITSTREAM.CONFIG.BPI_SYNC_MODE TYPE2 [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN DIV-2 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
set_property CONFIG_MODE BPI16 [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 2.5 [current_design]

set_property -dict {PACKAGE_PIN AD12 IOSTANDARD DIFF_SSTL15} [get_ports sys_clk_p_i]
set_property -dict {PACKAGE_PIN AD11 IOSTANDARD DIFF_SSTL15} [get_ports sys_clk_n_i]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS15} [get_ports cpu_rst_i]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS25} [get_ports uart_rx_i]
set_property -dict {PACKAGE_PIN K24 IOSTANDARD LVCMOS25} [get_ports uart_tx_o]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS25} [get_ports sm_fan_tach_i]
set_property -dict {PACKAGE_PIN L26 IOSTANDARD LVCMOS25} [get_ports sm_fan_pwm_o]
set_property -dict {PACKAGE_PIN AC6 IOSTANDARD LVCMOS15} [get_ports {gpio_sw_i[6]}]
set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS15} [get_ports {gpio_sw_i[5]}]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS15} [get_ports {gpio_sw_i[4]}]
set_property -dict {PACKAGE_PIN AG5 IOSTANDARD LVCMOS15} [get_ports {gpio_sw_i[3]}]
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS15} [get_ports {gpio_sw_i[2]}]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS15} [get_ports {gpio_led_o[7]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS15} [get_ports {gpio_led_o[6]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS15} [get_ports {gpio_led_o[5]}]
set_property -dict {PACKAGE_PIN AE26 IOSTANDARD LVCMOS15} [get_ports {gpio_led_o[4]}]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVCMOS15} [get_ports {gpio_led_o[3]}]
set_property -dict {PACKAGE_PIN AC9 IOSTANDARD LVCMOS15} [get_ports {gpio_led_o[2]}]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS15} [get_ports {gpio_led_o[1]}]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS15} [get_ports {gpio_led_o[0]}]

set_false_path -from [get_ports cpu_rst_i]
set_false_path -from [get_ports uart_rx_i]
set_false_path -to [get_ports uart_tx_o]
set_false_path -from [get_ports sm_fan_tach_i]
set_false_path -to [get_ports sm_fan_pwm_o]
set_false_path -from [get_ports {gpio_sw_i[*]}]
set_false_path -to [get_ports {gpio_led_o[*]}]
