set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports clk_i]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports rst_n_i]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports btn_n_i]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports led1_o]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports led2_o]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports led3_o]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports led4_o]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports uart_rx_i]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports uart_tx_o]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports uart1_rx_i]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports uart1_tx_o]

set_false_path -from [get_ports rst_n_i]
set_false_path -from [get_ports btn_n_i]

set_false_path -to [get_ports led1_o]
set_false_path -to [get_ports led2_o]
set_false_path -to [get_ports led3_o]
set_false_path -to [get_ports led4_o]

set_false_path -from [get_ports uart_rx_i]
set_false_path -to   [get_ports uart_tx_o]

set_false_path -from [get_ports uart1_rx_i]
set_false_path -to   [get_ports uart1_tx_o]
